# Configuración AFIP para Producción
afip.environment=prod
afip.cuit.emisor=20449965493
afip.p12.path=conf/certs/afip-prod.p12
afip.p12.password=tu_password_aqui
afip.url.wsaa=https://wsaa.afip.gov.ar/ws/services/LoginCms
afip.url.wsfe=https://servicios1.afip.gov.ar/wsfev1/service.asmx
afip.url.ws_sr_constancia_inscripcion=https://aws.afip.gov.ar/sr-padron/webservices/personaServiceA5

# Python Backend URL (interno)
python.backend.url=http://127.0.0.1:8000
python.backend.username=tu_usuario
python.backend.password=tu_password
